apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name   : devops2-eks
  version: "1.30"
  region : us-east-1
  
vpc:
 subnets:
   public:
      us-east-1a: { id: subnet-0a40e7beb104e25cb }
      us-east-1b: { id: subnet-040425d052d1d07d1 }

   private:
      us-east-1a: { id: subnet-066502d8331d198cf }
      us-east-1b: { id: subnet-0a11d78468a9e28a5 }

managedNodeGroups:
  - name             : worker-group-1
    instanceType     : m5.large
    desiredCapacity  : 2
    labels           : { role: worker1 }   
    volumeSize       : 80
    privateNetworking: true
    
  - name             : worker-group-2
    instanceType     : r5.large
    desiredCapacity  : 2
    volumeSize       : 100
    labels           : { role: worker2 }    
    privateNetworking: true    